pets/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

from rest_framework import routers


from pets import views as api_views
# from api_test import views as test_views
# router = routers.DefaultRouter()
# router.register(r'pets', views.PetView, base_name='pets')

urlpatterns = [

    #API urls
    url(r'^signup/', api_views.Signup.as_view(), name='signup' ),
    url(r'^login/', api_views.Login.as_view(), name='login' ),
    url(r'^logout/', api_views.Logout.as_view(), name='logout' ),

    url(r'^pets/$', api_views.PetView.as_view(), name='pets'),
    url(r'^pets/(?P<pk>[0-9]+)/$', api_views.PetView.as_view(), name='pets'),

]

technical_test/urls.py
# from django.conf.urls.defaults import *
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from rest_framework import routers

from pets import views as api_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

#API url request
    url(r'^user/', include('pets.urls', namespace='user')),

#main urls 
    url(r'^$', TemplateView.as_view(template_name="pets/login.html")),
    url(r'^signup/$', TemplateView.as_view(template_name="pets/signup.html")),
    # url(r'^login/$', TemplateView.as_view(template_name="pets/login.html")),
    url(r'^dashboard/$', TemplateView.as_view(template_name="pets/dashboard.html")),


    # url(r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', {'url': '/static/images/favicon.ico'}),
]


"""
Customized the django admin site header, index_title and site_title changes.
"""
admin.site.site_header = 'Pet portal administration'
admin.site.index_title = 'Pet portal administration'
admin.site.site_title = 'Pet portal admin'

pets/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

class Pet(models.Model):
    PET_TYPE = (
        ('D', 'Dog'),
        ('C', 'Cat'),
    )
    
    name = models.CharField(max_length=100, null=True, blank=True)
    birthday = models.DateField(null=True, blank=True)
    pet_type = models.CharField(max_length=1, choices=PET_TYPE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    

    def __str__(self):
        return "%s :: %s" % (self.name, self.pet_type)

pets/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login

from rest_framework import status, viewsets
from rest_framework.permissions import IsAuthenticated, AllowAny, IsAuthenticatedOrReadOnly
from rest_framework.authtoken.models import Token
from rest_framework.response import Response
from rest_framework.views import APIView

from .serializers import PetSerializer, SignupSerializer, LoginSerializer, LogoutSerializer
from .models import Pet



def dashboard(request):
    return render(request, 'pets/dashboard.html')


@login_required
def my_pets(request):
    mypets = Pet.objects.filter(owner=request.user)
    return render(request, 'pets/my_pets.html', {'mypets':mypets})

# @login_required
class PetView(APIView):
    """ 
        Only Authenticate User perform CRUD Operations
    """
    permission_classes = (IsAuthenticated,)
    model = Pet
    serializer_class = PetSerializer

    def get(self, request, pk=None):
      userdata = self.model.objects.all()
      if pk != None:
        userdata = userdata.filter(id= pk)
      else:
        userdata = userdata.filter(owner=self.request.user)
      serializer = PetSerializer(userdata, many=True)
      return Response(serializer.data)  

    def post(self, request):
      serializer = PetSerializer(data= request.data )
      serializer.is_valid(raise_exception=True)
      serializer.save(owner=self.request.user)
      return Response(serializer.data)

    def put(self, request, pk):
      userdata = Pet.objects.get(pk= pk)
      serializer = PetSerializer(userdata, data=request.data, partial=True)
      if serializer.is_valid():
        serializer.save()
        return Response(serializer.data)
      return Response(serializer.errors)

    def delete(self, request, pk=None):
      self.model.objects.get(pk= pk).delete()
      return Response({
        "status": 202,
        "success" : True,
        "message" : "Successfully Deleted.",
         })


''' Signup '''
class Signup(APIView):
    permission_classes = (AllowAny,)
    serializer_class = SignupSerializer

    def post(self, request):

        serializer = self.serializer_class(data = request.data)
        if serializer.is_valid(raise_exception=True):

          user = serializer.save()

          username = user.username
          raw_password = user.password
          #again set password in HASH format
          user.set_password(raw_password)

          user.save()
          
          user = authenticate(username=username, password=raw_password)
          
          token, created = Token.objects.get_or_create(user=user) 
      
          headers = { 'access_token': token.key }
          return Response({
            "status": status.HTTP_201_CREATED,
            "success" : True,
            "message" : "Successfully Created Your Account.",
          }, headers= headers )
        return Response(serializer.errors)


class Login(APIView):
  """
  IT's user login view. accepted method post. it's return always new token. and endpoint is /login.
  """
  permission_classes = (AllowAny,)
  serializer_class = LoginSerializer

  def post(self, request, *args, **kwargs):
    serializer = self.serializer_class(data=request.data)

    serializer.is_valid(raise_exception=True)
    user = serializer.validated_data['user']
    try:
      token, created = Token.objects.get_or_create(user=user)
      # UserDesktop.as_view()

    except Exception as e:
      pass
      
    headers = {
           'access_token' : token.key
           # 'Access-Control-Expose-Headers': 'access_token'
       }

    return Response({
      "status": status.HTTP_200_OK,
      "message" : 'Successfully login.'
      
    }, headers=headers)


''' Logout ''' 
class Logout(APIView):
  permission_classes = (AllowAny,)
  serializer_class = LogoutSerializer

  def post(self, request, *args, **kwargs):
    serializer = self.serializer_class(data = request.data)
    serializer.is_valid(raise_exception=True)
    token = serializer.validated_data['token']
    if token:
      token.delete()
    else:
      pass

    return Response({
      "status": status.HTTP_200_OK,
      "message" : 'Successfully logout.'
      })

templates/pets/base.html
 {% load static %}
 <!DOCTYPE html>

<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}    Pet Portal  {% endblock %}</title>

<link rel="shortcut icon" href="{%  static "pets/images/favicon.ico" %}">
<link rel="stylesheet" type="text/css" href="{% static 'pets/css/bootstrap.min.css' %}" />

<style>

  .logout-btn {
    display : none;
  }

    {% block stylesheet %}  



    {% endblock %}
</style>

</head>

<body>


<header>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button data-target="#header-menu" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="." class="navbar-brand value-brand">PET PORTAL</a>

      </div>
      <div class="collapse navbar-collapse" id="header-menu">

                <a href="/" title='Logout' class="logout-btn btn btn-default navbar-btn navbar-right">  Logout   </a>         
                <a href="/" title="Sign in" class="signin-btn btn btn-default navbar-btn navbar-right">Sign in</a>           
                <a href="/signup/" title="Sign up" class="signup-btn btn btn-primary navbar-btn navbar-right" style="margin-right:5px;">
                    Sign up </a>        
      </div>     
    </div>   
  </nav>
</header> 

<div id='content'>    {% block content %} {% endblock %} </div>

    <script src="{% static 'pets/js/jquery.min.js' %}"></script>
    <script src="{% static 'pets/js/bootstrap.min.js' %}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/0.5.0/sweet-alert.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/0.5.0/sweet-alert.css"/>

    {% block javascript %} {% endblock %}


  <nav class="footer navbar-fixed-bottom navbar-default">
    <div class="container">
    <div class="row">
      <div class="col-xs-12 legal">
      <br>
        <center> <span>© 2017 Pet Portal</span> </center>
      <br>
      </div>
     </div>
    </div>
</nav>

</body>
</html>

templates/pets/dashboard.html
{% extends 'pets/base.html' %}

{% load static %}

{% block title %} signup {% endblock %}


{% block stylesheet %} 
  <style>

  ul {
    border : 1px solid black;
  }


  li {  
    width : 80px;
    display: inline-block;

  }

  #showdata, #nodata {
    display : none;
  }

  #datewarn, #all_form_invalid   {
    color : red;
  }

.form-control {
    display: block;
    width: 220%;
    height: 34px;
    padding: 6px 12px;
    font-size: 14px;
    line-height: 1.42857143;
    color: #555;
    background-color: #fff;
    background-image: none;
    border: 1px solid #ccc;
    border-radius: 4px;
}

#table-head {
    font-size: 18px;
    font-style: oblique;
    font-weight: 900;
    font-synthesis: weight style;
    /*font-variant: inherit;*/

}




  </style>

{% endblock %}

{% block content %}


{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}


<div class='row'>
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading">
       <center> <h3 class="panel-title">Dashboard</h3> </center>
      </div>
      <div class="panel-body">

      <center id="get_url_link" data-get_url="{% url 'user:pets' %}"> 


        <div id= "nodata">
          <center>  <h3> No Record Available...  </h3> </center>
        </div>

        <div id="showdata" >
          <ul id='table-head'>

            <li>  Pet  </li>
            <li>  Name  </li>
            <li>  Birthday  </li>
            <li>  Update  </li>
            <li>  Delete  </li>
          </ul>
          <span id="details"></span>


       </div>

      </center>
        <br>
        <div id="midpart" class="form-group text-center col-md-4">
          <button type="button" class="btn btn-primary " data-toggle="modal" data-target="#CreateModal"> Create </button>
      
        </div>

      </div>
    </div>
  </div>
</div>




<!-- Create New Details Modal -->  
<div class="modal fade" id="CreateModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">

        <button type="button" class="pet_form_close close" data-dismiss="modal" aria-label="Close"> <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Pet Details Form</h4>
      </div>
    <div class="modal-body">
      <center>  <div id="all_form_invalid"></div> </center>
      <form id="pet_form" class="pet_form"  method="POST" >
        {% csrf_token %}

        <ul class="form">

          <li class="form-group" id="r1"> 
            <label for="name"> Pet Type</label>          
            <select name="pet_type" id="pet_type" class="btn btn-default form-control" required>
              <option value="C">Cat </option>
              <option value="D">Dog </option>
            </select> 
          </li>
          <br>
          <li class="form-group" id=r2> 
            <label for="name"> Pet Name </label>         
            <input class="form-control" id="name" type="text" name="name"  placeholder="Pet Name"  required>  
          </li> 
          <br>
          <li class="form-group" id=r3> 
            <label for="dob"> Birthday </label>    
            <input class="form-control" id="birthday" type="date" name="birthday" placeholder="DD-MM-YYYY"  onchange='check_Date()' required/> 
            <div id="datewarn" class="datewarn"></div> 
          </li>
        </ul>
        
        <div class="modal-footer">
          <button type="button" class="close_modal btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-success" id="submit" name="submit" onclick="return validateForm()">Submit</button>

        </div>
      </form>
    </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="Create_Success_Modal" tabindex=" -1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div id="success_m" class="modal-body">
        <h1 style="text-align:center"> <strong> Successfully</strong> Registered ! </h1>

      </div>
    </div>
  </div>
</div>



<!-- UPDATE MODAL -->

<div class="modal fade" id="UpdateModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"> <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"> Update Pet Details </h4>
      </div>
      <div class="modal-body" id="update_model_form" pet_id="">
        <center>  <div id="all_form_invalid"> </div> </center>
        <form id="update_form" class="pet-udpate-form"  method="POST" >
          {% csrf_token %}

          <ul class="form">

            <li class="form-group" id="r1"> 
              <label for="name"> Pet </label>          
              <select name="pet_type" id="pet_type" class="btn btn-default form-control pet_type"  required>
                <option value="C">Cat </option>
                <option value="D">Dog </option>
              </select> 
            </li>
            <br>
            <li class="form-group" id=r2> 
              <label for="name"> Pet Name </label>         
              <input class="form-control name" id="name" type="text" name="name"  placeholder="Pet Name" required>  
            </li> 
           <br>
            <li class="form-group" id=r3> 
              <label for="dob"> Birthday </label>    
              <input class="form-control birthday" id="birthday" type="date" name="birthday" placeholder="DD-MM-YYYY" onchange='return check_Date()' required/> <div id="datewarn" class="datewarn"></div>
            </li>

          </ul>

        <div class="modal-footer">
          <button type="button" class="close_modal btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-success" id="submit" name="submit" onclick="return validateForm()">Submit</button>
        </div>

        </form>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<!--successfully registered-->
<div class="modal fade" id="Update_Success_Modal" tabindex=" -1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div id="success_m" class="modal-body">
        <h1 style="text-align:center"> <strong> Successfully</strong> Update ! </h1>

      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="Delete_Success_Modal" tabindex=" -1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div id="success_m" class="modal-body">
        <h1 style="text-align:center"> <strong> Successfully</strong> Registered ! </h1>

      </div>
    </div>
  </div>
</div>

  
{% endblock %}




{% block javascript %}
  
<!-- <script type="text/javascript" src="{% static 'pets/js/signup.js' %}"></script> -->

<!-- jQuery library -->
<script type="text/javascript" src="{% static 'pets/js/dashboard.js' %}"></script>





{% endblock %}

templates/pets/login.html
{% extends 'pets/base.html' %}

{% load static %}

{% block title %} login {% endblock %}


{% block content %}


{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}


<div class='row'>
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Login </h3>
      </div>
      <div class="panel-body">


          <form id='login_form' action ="." data-url="{% url 'user:login'  %}"  method='POST' >
          {{ form.errors }}
          {% csrf_token %}
    
          <div class="panel-group">
              <label class="control-label" for="email"> Email </label>
              <input type="email" class="form-control"  id="id_email" name="email" required>
              </div>

          <div class="panel-group">
              <label class="control-label" for="id_password"> Password </label>
              <input type="password" class="form-control"  id="id_password" name="password" required>
            </div>

         <!-- <button type="submit" class="btn btn-success"  onclick="return Validate()" >Submit</button> -->
          <input type='submit' name='submit'>
          </form>



      </div>
    </div>
  </div>
</div>



  
{% endblock %}




  


{% block javascript %}
  
<script type="text/javascript" src="{% static 'pets/js/login.js' %}"></script>





{% endblock %}

templates/pets/signup.html
{% extends 'pets/base.html' %}

{% load static %}


{% block title %} SignUp {% endblock %}


{% block content %}

  {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}

  <div class='row'>
    <div class="col-md-6 col-md-offset-3">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"> Signup</h3>
        </div>
        <div class="panel-body">

 <form id='signup_form' action ="." data-url="{% url 'user:signup'  %}"  method='POST' >
          {{ form.errors }}
          {% csrf_token %}

                <div class="panel-group">
                    <label class="control-label" for="username"> User Name </label>
                    <input type="text" class="form-control"  id="usesrname" name="username" required>
                    </div>

    
                <div class="panel-group">
                    <label class="control-label" for="email"> Email </label>
                    <input type="email" class="form-control"  id="id_email" name="email" required>
                    </div>

                <div class="panel-group">
                    <label class="control-label" for="id_password"> Password </label>
                    <input type="password" class="form-control"  id="id_password" name="password" required>
                </div>

                <div class="panel-group">
                  <label class="control-label" for="confirm-pass"> Confirm Password </label>
                  <input type="password" class="form-control" id="confirm-pass" name="confirm-pass" required>
                  <div id='gen_error'>                </div>

         <button type="submit" name='submit' class="btn btn-success"  onclick="return Validate()" >Submit</button>
          </form>


        </div>
      </div>
    </div>
  </div>



{% endblock %}




{% block javascript %}

  <script type="text/javascript" src="{% static 'pets/js/signup.js' %}"></script>

{% endblock %}